apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rest-api
  name: rest-api
spec:
  containers:
  - name: server
    image: ghcr.io/tarkov-database/rest-api:2.14.1
    env:
    - name: JWT_AUDIENCE
      value: localhost
    - name: SERVER_PORT
      value: "9000"
    - name: JWT_ALG
      value: HS256
    - name: JWT_EXPIRATION
      value: 1h
    - name: JWT_KEY
      value: FhLpkUvWbfVCb5Pp69qvBcTH
    - name: MONGO_URI
      value: mongodb://localhost:27017/rest-api
    - name: MONGO_DB
      value: rest-api
    ports:
    - containerPort: 9000
      hostPort: 9000
      protocol: TCP
  - name: mongo
    image: docker.io/library/mongo:4.4
